apiVersion: v1
kind: Service
metadata:
  name: samba-ad
  labels:
    app: samba-ad
spec:
  selector:
    app: samba-ad
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
    - protocol: TCP
      port: 445
      targetPort: 445
  type: {{ .Values.service.type }}
